version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: sga_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sga
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - sga_network

volumes:
  pg_data:
    driver: local

networks:
  sga_network:
    driver: bridge
